runmode: debug                 # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: mae_apiserver              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5  #46字符的随机字符串
casbinmodel: conf/casbinmodel.conf
kubeconfig: conf/admin.kubeconfig
tokenEffectiveTime: 60  #token默认有效期时长，默认60分钟,请求时可以传参改变改值
tls:
  addr: :8081
  cert: conf/example.com+4.pem
  key: conf/example.com+4-key.pem
log:
  writers: file
  logger_level: DEBUG
  logger_file: log/mae.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  #数据库名，跑之前提前建好
  name: mae
  #数据库地址
  addr: 127.0.0.1:3306
  #用户名
  username: root
  #密码
  password: pqc19960320

mail:
  #邮件服务器地址
  host: smtp.qq.com
  #邮件服务端口
  port: 25
  username: 3480437308@qq.com　
  senderNickName: Mae notification robot　
  password: iifwjwzfjxvxchig
  #与邮件服务器连接的最大时长，默认30秒，即30秒之内没有需要发送的邮件则断开与邮件服务器的连接
  maxFreeTime: 30
  #邮件通道缓冲区大小，默认20
  chanCache: 20
  #认证邮件中的链接的有效期时长,默认30分钟之后认证邮件过期
  confirmTime: 30

